# 1. Load Libraries
# --------------------------

import scvelo as scv
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Set plotting parameters for scVelo/Scanpy
scv.settings.set_figure_params('scvelo') # Use scVelo's default styles
sc.settings.verbosity = 3  # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()

print(f"scVelo version: {scv.__version__}")
print(f"Scanpy version: {sc.__version__}")

# 2. Load Data
# ------------
# Load .loom file generated by velocyto/kb-python:
# adata = scv.read('path/to/your_sample.loom', cache=True)
# adata.var_names_make_unique() # Ensure unique gene names

# Load built-in pancreas dataset
# AnnData object already contains 'spliced' and 'unspliced' layers
# Also has pre-computed PCA, neighbors, UMAP, and clusters from a standard Scanpy workflow
adata = scv.datasets.pancreas()

print("Loaded AnnData object:")
print(adata)
# AnnData object with n_obs × n_vars = 3696 × 27998
#     obs: 'clusters_coarse', 'clusters', 'S_score', 'G2M_score'
#     var: 'highly_variable_genes'
#     uns: 'clusters_coarse_colors', 'clusters_colors', 'day_colors', 'neighbors', 'pca', 'rank_genes_groups'
#     obsm: 'X_pca', 'X_umap'
#     layers: 'spliced', 'unspliced'  <-- Essential for velocity!
#     obsp: 'connectivities', 'distances'

# Show existing clustering on UMAP (from standard analysis)
sc.pl.umap(adata, color='clusters', title='Pre-computed Clusters', save='_01_umap_clusters.png')

# 3. Preprocessing for RNA Velocity
# ---------------------------------
# Basic filtering and normalization tailored for velocity analysis.
# Finds genes with sufficient spliced/unspliced counts.
# Normalizes counts per cell. Selects highly variable genes based on velocity criteria.
scv.pp.filter_and_normalize(adata,
                            min_shared_counts=20, # Min counts in both spliced/unspliced layers
                            n_top_genes=2000)     # Select top HVGs for velocity

# Compute first and second order moments (needed for dynamical model)
# Calculates moments for velocity estimation across nearest neighbors in PCA space
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)


# 4. Estimate RNA Velocity
# ------------------------
# scVelo offers two main models:
# a) Steady-State Model: Assumes constant transcriptional state. Simpler, faster.
# b) Dynamical Model: Models full splicing kinetics. More complex, slower, but often more accurate,
#    especially for dynamic processes. It can capture induction and repression phases.

# Dynamical Model:
print("Running dynamical model recovery...")
scv.tl.recover_dynamics(adata, n_jobs=8) # n_jobs for parallelization if possible

print("Calculating velocity vectors...")
# Calculate velocity vectors for each cell based on the fitted dynamical model
scv.tl.velocity(adata, mode='dynamical')

# Calculate velocity graph (transitions based on velocity vectors)
# Embeds velocities into a transition matrix using cosine correlation between
# velocity vectors and potential state changes.
scv.tl.velocity_graph(adata)

print("Velocity estimation complete.")

# If the dynamical model fails or to quick check, use the steady-state model:
# scv.tl.velocity(adata, mode='deterministic') # or 'stochastic'


# 5. Visualize Velocity Results
# -----------------------------

# Visualize velocities as streamlines projected onto the UMAP embedding
# Arrows indicate the inferred direction and speed of cell state changes
print("Plotting velocity stream...")
scv.pl.velocity_embedding_stream(adata,
                                 basis='umap',           # Embedding to use (e.g., 'umap', 'tsne')
                                 color='clusters',       # Color cells by cluster (or other metadata)
                                 title='RNA Velocity Stream on UMAP',
                                 legend_fontsize=8,
                                 save='_02_velocity_stream.png')

# Arrows show the local average velocity direction.
# Follow arrows to see predicted cell trajectories. Arrow length relates to speed.
# In the pancreas example, velocities pointing from Ductal/Ngn3 low EP
# towards endocrine cell fates (Alpha, Beta, Delta, Epsilon).

# Alternative visualization: Grid-based velocity plot
# scv.pl.velocity_embedding_grid(adata, basis='umap', color='clusters', arrow_length=3, arrow_size=2, dpi=120, save='_03_velocity_grid.png')

# Visualize velocity confidence (optional)
# scv.tl.velocity_confidence(adata)
# scv.pl.scatter(adata, c='velocity_confidence', cmap='coolwarm', perc=[2,98], save='_04_velocity_confidence.png')


# 6. Inspect Gene-Specific Dynamics
# ---------------------------------

# Investigate velocity patterns for individual genes driving the dynamics
# Use genes known to be important in pancreas development or top likelihood genes from dynamical model

# Example genes for pancreas endocrinogenesis
genes_of_interest = ['Cpe', 'Ghrl', 'Nkx2-2', 'Neurog3', 'Ins1', 'Ins2', 'Gcg', 'Sst']

# Plot gene expression, velocity, and phase portrait for selected genes
for gene in genes_of_interest:
    if gene in adata.var_names:
        print(f"Plotting velocity for gene: {gene}")
        scv.pl.velocity(adata, var_names=[gene], color='clusters', dpi=100, save=f'_05_velocity_phase_{gene}.png')
        # Phase portrait: Shows spliced vs unspliced counts. Cells above the diagonal
        # are generally up-regulating the gene (more unspliced than steady-state),
        # cells below are down-regulating. The inferred steady-state line is shown.
        # Arrows show observed velocity for each cell.

        scv.pl.velocity_embedding(adata, basis='umap', var_names=[gene], color='clusters', arrow_color='black', arrow_size=1, dpi=100, save=f'_06_velocity_umap_{gene}.png')
        # UMAP colored by velocity value for the specific gene (red=positive velocity/upregulation, blue=negative/downregulation)


# 7. Additional Analyses
# -------------------------------
# - Latent Time: Infer a continuous measure of cell state based on transcriptional dynamics
#   scv.tl.latent_time(adata)
#   scv.pl.scatter(adata, color='latent_time', color_map='gnuplot', size=80, save='_07_latent_time.png')

# - PAGA Velocity Graph: Combine velocity with PAGA graph partitioning for trajectory inference
#   (Requires running sc.tl.paga first)
#   scv.tl.paga(adata, groups='clusters')
#   scv.pl.paga(adata, basis='umap', size=50, alpha=.1, min_edge_width=2, node_size_scale=1.5, save='_08_paga_velocity.png')


# 8. Saving Results
# -----------------
# The AnnData object now contains velocity information in adata.layers['velocity']
# and other related fields (e.g., adata.uns['velocity_graph'])
# You can save the updated AnnData object
# results_file = 'pancreas_scvelo_processed.h5ad'
# adata.write(results_file)
# print(f"RNA velocity analysis complete. Results saved to {results_file}")

print("\nBasic scVelo RNA velocity analysis workflow completed.")
